HRNET_MODEL:
  ALIGN_CORNERS: true
  PRETRAINED: "/home/akhil/Documents/hrnetv2_w48_imagenet_pretrained.pth"
  CONFIGURATION:
    STEM_STRIDE: 4
    STEM_INPUT_CHANNEL: 3
    STEM_OUTPUT_CHANNEL: 64
    STAGE1:
      NUM_MODULES: 1
      NUM_RANCHES: 1
      BLOCK: BOTTLENECK
      NUM_BLOCKS:
        - 4
      NUM_CHANNELS:
        - 64
      FUSE_METHOD: SUM
    STAGE2:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      BLOCK: BASIC
      NUM_BLOCKS:
        - 4
        - 4
      NUM_CHANNELS:
        - 48
        - 96
      FUSE_METHOD: SUM
    STAGE3:
      NUM_MODULES: 4
      NUM_BRANCHES: 3
      BLOCK: BASIC
      NUM_BLOCKS:
        - 4
        - 4
        - 4
      NUM_CHANNELS:
        - 48
        - 96
        - 192
      FUSE_METHOD: SUM
    STAGE4:
      NUM_MODULES: 3
      NUM_BRANCHES: 4
      BLOCK: BASIC
      NUM_BLOCKS:
        - 4
        - 4
        - 4
        - 4
      NUM_CHANNELS:
        - 48
        - 96
        - 192
        - 384
      FUSE_METHOD: SUM
  PYRAMID_CHANNELS:
    - 64
    - 512
    - 512
    - 1024
    - 1024
OCRNET_MODEL:
  RAW_IN_CHANNELS: 720
  NUM_CLASSES: 17
  PIXEL_REP_CHANNELS: 512
  KEY_CHANNELS: 256




    
